spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: null
    driver-class-name: org.h2.Driver
      mvc:    view:      prefix: /views/
      suffix: .jsp
server:  port: 9090
    